/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        lblCurrentUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReceiver = new javax.swing.JMenu();
        jmiAddReceiver = new javax.swing.JMenuItem();
        jmiShowAllReceivers = new javax.swing.JMenuItem();
        jMenuBook = new javax.swing.JMenu();
        jmiaddBook = new javax.swing.JMenuItem();
        jmiShowAllBook = new javax.swing.JMenuItem();
        jMenuBookstore = new javax.swing.JMenu();
        jmiaddBookstore = new javax.swing.JMenuItem();
        jmiShowAllBokstore = new javax.swing.JMenuItem();
        jMenuOrder = new javax.swing.JMenu();
        jmiAddNewPurchaseOrder = new javax.swing.JMenuItem();
        jmiShowAllPurchaseOrder = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuReceiver.setText("Prijemnica");

        jmiAddReceiver.setText("Dodaj novu");
        jMenuReceiver.add(jmiAddReceiver);

        jmiShowAllReceivers.setText("Prikazi sve");
        jMenuReceiver.add(jmiShowAllReceivers);

        jMenuBar1.add(jMenuReceiver);

        jMenuBook.setText("Knjiga");

        jmiaddBook.setText("Dodaj novu");
        jMenuBook.add(jmiaddBook);

        jmiShowAllBook.setText("Prikazi sve");
        jMenuBook.add(jmiShowAllBook);

        jMenuBar1.add(jMenuBook);

        jMenuBookstore.setText("Knjižara");

        jmiaddBookstore.setText("Dodaj novu");
        jMenuBookstore.add(jmiaddBookstore);

        jmiShowAllBokstore.setText("Prikazi sve");
        jMenuBookstore.add(jmiShowAllBokstore);

        jMenuBar1.add(jMenuBookstore);

        jMenuOrder.setText("Porudžbenica");

        jmiAddNewPurchaseOrder.setText("Dodaj novu");
        jMenuOrder.add(jmiAddNewPurchaseOrder);

        jmiShowAllPurchaseOrder.setText("Prikazi sve");
        jMenuOrder.add(jmiShowAllPurchaseOrder);

        jMenuBar1.add(jMenuOrder);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(lblCurrentUser)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBook;
    private javax.swing.JMenu jMenuBookstore;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuOrder;
    private javax.swing.JMenu jMenuReceiver;
    private javax.swing.JMenuItem jmiAddNewPurchaseOrder;
    private javax.swing.JMenuItem jmiAddReceiver;
    private javax.swing.JMenuItem jmiShowAllBokstore;
    private javax.swing.JMenuItem jmiShowAllBook;
    private javax.swing.JMenuItem jmiShowAllPurchaseOrder;
    private javax.swing.JMenuItem jmiShowAllReceivers;
    private javax.swing.JMenuItem jmiaddBook;
    private javax.swing.JMenuItem jmiaddBookstore;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables
   
public void jmiBookstoreNewAddActionListener(ActionListener actionListener) {
        jmiaddBookstore.addActionListener(actionListener);
    }

    public void jmiBookNewAddActionListener(ActionListener actionListener) {
        jmiaddBook.addActionListener(actionListener);
    }

    public void jmiBookstoreShowAllActionListener(ActionListener actionListener) {
        jmiShowAllBokstore.addActionListener(actionListener);
    }

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }

    public void jmiBookShowAllActionListener(ActionListener actionListener) {
        jmiShowAllBook.addActionListener(actionListener);
    }
    public void jmiAddNewReceiverAddActionListeners(ActionListener actionListener){
        jmiAddReceiver.addActionListener(actionListener);
    }
     public void jmiReceiverShowAllAddActionListener(ActionListener actionListener) {
        jmiShowAllReceivers.addActionListener(actionListener);
    }
    public void jmiOrderNewAddActionListener(ActionListener actionListener) {
       jmiAddNewPurchaseOrder.addActionListener(actionListener);
    }
    
    public void jmiOrderShowAllAddActionListener(ActionListener actionListener) {
       jmiShowAllPurchaseOrder.addActionListener(actionListener);
    }
   

}
